### ISSUE TITLE
Licensing for openshift-maven-plugin

### ISSUE THREAD

**Issue by jim-minter** [worldline/openshift-maven-plugin#1]
Hi,

I'd very much like to extend this plugin to make use of the new binary deployment
feature made available in OpenShift's November release ( https://www.openshift.com/blogs/online-release-for-november-2013 ).

Are you able to confirm the licence that covers the existing code, e.g. Apache?  Could a suitable LICENSE file be added to the repository to confirm this?

My intention would be that any additions I made would be fully open source, of course.  If I may, I'd very much like to bring the project to the attention to the OpenShift community as I think it could be very useful to a lot of people.

Many thanks,

Jim Minter

**Comment by Filirom1** [comment]
Of course it should be the same license than OpenShift.

Done by https://github.com/worldline/openshift-maven-plugin/commit/04212f50a2a745092a658332a9d04d485d3a3a7e

**Comment by jim-minter** [comment]
Thanks for the quick response!
